print.optbdmaeAT<-function(x,...)
{
cat("\n        ---------------------------------------    \n")
cat("Title:  ",x$Optcrit,"-optimal or near-optimal block design        ","Date: ", format(Sys.time(), "%a %b %d %Y %H:%M:%S"),"\n",sep="")
cat("        ---------------------------------------    \n")
cat("Call:\n")
print(x$call)
#cat("\nparametric combintaions:\n")
#cat("\nNumber of treamtments:         ", x$v, "\n")
#cat("Number of blocks:              ", x$b, "\n")
#cat("Theta value:                   ",  x$theta, "\n")
#cat("Number of replications:        ",  x$nrep, "\n")
#cat("Number of exchange iteration:  ", x$itr.cvrgval, "\n")
#cat("Algorithm used:                ", x$Alg, "\n")
#cat("OPtimality criterion used:      ", x$Optcrit, "-optimality criteria\n",sep="")
cat("\nResultant ",x$Optcrit,"-optimal or near-optimal block design:\n",sep="")
cat("\n")
print(data.frame(x$OptdesF))
cat("\n", x$file_loc2,"\n", x$file_loc,"\n")
cat("\n")
}
